import '@/styles/dashboard/globals.css'
import { Chakra } from '@/_components/providers/ChakraProvider'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

import { TRPCReactProvider } from '@/trpc/react'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <body className={`font-sans ${inter.variable}`}>
      <TRPCReactProvider cookies={cookies().toString()}>
        <Chakra>{children}</Chakra>
      </TRPCReactProvider>
    </body>
  )
}
